import { DM_Sans } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/ThemeProvider'
import Header from '@/components/Header';
import { SpeedInsights } from '@vercel/speed-insights/next';

const inter = DM_Sans({ subsets: ['latin'], weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900', '1000'] });

export const metadata = {
  title: 'Mistwood',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" style={{ colorScheme: 'light' }}>
      <body className={inter.className}>
      <ThemeProvider attribute='class' defaultTheme='system'>
      <Header />
        {children}
        <SpeedInsights />
      </ThemeProvider>
        </body>
    </html>
  )
}
