import { DM_Sans,Comic_Neue } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/ThemeProvider'

const inter = DM_Sans({ subsets: ['latin'], weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900', '1000'] });
const comic = Comic_Neue({ subsets: ['latin'], weight: ['300', '400', '700'] });

export const metadata = {
  title: 'Mistwood',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" style={{ colorScheme: 'light' }}>
      <body className={inter.className}>
      <ThemeProvider attribute='class' defaultTheme='system'>
        {children}
      </ThemeProvider>
        </body>
    </html>
  )
}
