import { DM_Sans } from 'next/font/google'
import './globals.css'

const inter = DM_Sans({ subsets: ['latin'],weight:['100','200','300','400','500','600','700','800','900','1000'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
